### ISSUE TITLE
ovh-ebtables-agent

### ISSUE THREAD

**Issue by xelfe** [mangelajo/ovh-ebtables-agent#4]
give this error;
Traceback (most recent call last):
  File "/bin/ovh-ebtables-agent", line 6, in <module>
    from ovhagent.ovh_ebtables_agent import main
  File "/usr/lib/python2.7/site-packages/ovhagent/ovh_ebtables_agent.py", line 9, in <module>
    from neutron.openstack.common import log as logging
ImportError: cannot import name log

**Comment by mangelajo** [comment]
oh, may be we should try:

try: 
    from neutron.openstack.common import log as logging
except ImportError:
    from oslo_logging import log as logging

That changed for kilo, we now use the oslo library.
